// Code generated by go-bindata.
// sources:
// conf/app.ini
// DO NOT EDIT!

package bindata

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _confAppIni = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x6c\x92\x41\x8f\x9b\x30\x10\x85\xef\xf3\x2b\xe6\x42\x6f\x05\xb2\x87\xed\x2a\x92\x55\x6d\xb5\x8d\x72\x49\x85\x42\xdb\x4b\xc4\xc1\x8b\x87\x8d\x55\xc2\x58\xf6\x38\xca\xcf\xaf\x0c\x89\x02\xab\x5c\xbf\xf7\x98\xe1\xcd\xf3\x41\x3b\xd7\xc0\xab\x73\xbf\xf4\x89\xd4\x4f\xf3\x41\x55\xe5\xb9\x4b\xe4\x2f\xf9\x60\x79\x50\x65\x5e\xe6\x2b\xd8\xc7\x61\xc7\x86\x94\xa1\x33\xc0\x21\x90\x3f\x93\x6f\x60\x2b\xe2\x5e\x8d\xf1\xa8\x30\xd9\xca\xbc\x1c\x51\xc5\x5e\x50\xe1\x4b\xf9\x52\x02\x1c\x9c\xe7\xce\xf6\xd4\x40\x51\xe0\x6a\x8d\x3d\xb7\xba\xff\x9a\x08\xd4\xfa\x4c\x69\x2a\x2a\x5c\x41\xe5\x59\xb8\xe5\x1e\x15\x1e\x45\x5c\x80\x2d\x07\x59\xa1\xc2\x2c\xac\x8b\x22\x0b\x79\x16\xd6\x99\x19\xe9\xd3\x9d\x26\x54\x4d\x0b\xfe\xf8\xf4\x6d\x61\xe8\x3d\x7e\x14\x2e\x6d\x2d\xae\xab\x61\x4b\xda\x3d\x90\x8f\xa4\x1d\xfc\xe8\xb9\xfd\xf7\x40\x7c\x4f\x1c\x76\x51\xe8\xf2\x40\x3d\x25\x0e\x75\xec\x3a\x7b\x95\xbf\x07\x6a\x79\x30\x41\x65\xe6\x8b\xd8\x13\x71\x14\x95\x19\x80\x37\xea\x74\xec\xa5\x9e\xd4\x14\xb5\xbc\xb1\xdf\x93\x0d\x15\x3e\x97\xb0\xd3\x97\xbb\xe7\x79\x76\xb8\x7c\xba\xde\x35\xe5\xc6\xf6\x54\x79\xea\xec\x05\xd5\x98\x6b\x01\xc6\x30\x0b\x32\x06\x58\x90\xe5\xe0\x3c\x88\x16\xdb\x36\xb0\xa9\x3f\x35\x00\x9b\xfa\x8d\x4f\xda\x0e\xe9\x9f\x9f\xbe\xe5\xd3\x43\xd8\xd4\x7b\xea\xb5\xd8\x33\x55\x5a\x8e\xa8\xd0\x53\xe0\xe8\x5b\x9a\xcd\xf5\x1c\x85\x1a\xd8\x33\x4b\xaa\xf8\x6a\xcc\x0b\x1f\x87\x74\x99\x5b\x94\x99\x36\x2f\x6a\x86\xef\x05\xcd\xe0\xac\x98\x19\x9d\x0a\x01\xf8\x1f\x00\x00\xff\xff\x2e\x25\xdb\xa0\xd2\x02\x00\x00")

func confAppIniBytes() ([]byte, error) {
	return bindataRead(
		_confAppIni,
		"conf/app.ini",
	)
}

func confAppIni() (*asset, error) {
	bytes, err := confAppIniBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "conf/app.ini", size: 722, mode: os.FileMode(420), modTime: time.Unix(1557053004, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"conf/app.ini": confAppIni,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"conf": &bintree{nil, map[string]*bintree{
		"app.ini": &bintree{confAppIni, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

